server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xinfei?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 10.6.11.18
    password: Hangzhou@123


#自定义配置
xinfei:
  freemarker:
    baseUrl: http://localhost/
  upload:
    path: D:/home/roylion/file/images/
    prefixUrl: http://localhost/file/images/
