server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://47.100.10.104:3306/xinfei?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lgx@pass
  redis:
    host: 10.6.11.18
    password: Hangzhou@123


#自定义配置
xinfei:
  freemarker:
    baseUrl: http://www.roylion.cn/
  upload:
    path: /root/file/images/
    prefixUrl: http://www.roylion.cn/file/images/
