
spring:
  freemarker:
    suffix: .html
    cache: false
  profiles:
    active: dev

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#自定义配置
xinfei:
  upload:
    thumbs:
      width: 150
      height: 105
